### ISSUE TITLE
seek的问题

### ISSUE THREAD

**Issue by yangq1990** [dayoio/codec-as3#9]
你好，我想请教一个问题。seek到某一位置，从离seek点最近的关键帧开始，把mdat box中的nalu data抽取出来，怎么把这部分数据封装成flv? 我尝试过添加 flv header，以及重新添加sps、pps，依然无法流畅播放，音视频会不同步，请问这个改怎么处理。是添加sps、pps时时间戳不对导致的么？如果sps、pps时间戳不从0开始，应该设置为seek的keyframeTime么？

**Comment by dayoio** [comment]
实时加载还是啥？
如果图像声音都能播了，那基本数据应该是拿对了，不同步那就是时间戳不对咯~
看一下stts和ctts有没解析错误~   如果有ctts那flv的tag就不一定在前面就先显示~

**Comment by yangq1990** [comment]
hi，感谢回复。在不seek的时候，可以正常播放，音视频同步，seek后现在是有图像也有声音，但是音视频不同步。请问seek后该怎么对齐video frame和audio frame的timestamp，像没拖动时那样？我这边处理的是是让seek之后的nalu data的 vframe.timestamp - seekKeyframeTime*1000，请问这时改怎么处理音频帧的timestamp?

**Comment by dayoio** [comment]
太少信息了~ = =  不知道你的环境和怎么解析的~
整个视频解析还是数据流？
视频音频的**帧信息和帧偏移**都在stbl box里~ 这个要解析对~

**Comment by yangq1990** [comment]
可能我描述的不清晰，换种表达。按照codec-as3项目里的做法，mp4的帧信息，存储在 _mp4Codec.frames 这个数组里，如果是从头开始播放，就遍历这个数组，根据dataType  offset size  timestamp 依次生成flv video tag or audio tag，然后写入到bytearray，交给netstream播放，这样做是音视频同步的，可以正常播放。

现在假如timestamp为100000的frame是 keyframe，我想从这个timestamp开始（不是从头）获取mp4 nalu data并封装成flv tag，最后形成一个完整的flv文件，请问这个时候怎么控制音视频同步？如何找到跟这个keyframe对应的音频帧的timestamp？

对于flash，当使用数据生成模式播放视频，seek后，netstream.time是从0开始变化，假如离seek位置最近的关键帧的time是A，我猜测flash内部是将此关键帧后面的视频帧的timestamp都减去A，同时找到与此关键帧对应的音频帧，假如其timestamp为B，将此音频帧后面的音频帧的timestamp都减去B，以此来实现seek后的音视频同步。不过由于flash的源代码是不开源的，我也不确定，只是猜测而已。

或者说，从某一个时间点（不是从0）开始，把mp4转封装成flv，控制音视频同步是否有别的思路和实现？

**Comment by dayoio** [comment]
既然有全部帧的信息和数据了，跳的时候减去相同的时间不就行了？  
如果是整个视频解析 丢到appendBytes里 有关键帧是直接可以跳的~
#1
